export default {
  RECEIVE_POSTS: 'RECEIVE_POSTS',
  REFRESH_POSTS: 'REFRESH_POSTS',
  TOGGLE_POSTS_LOADING: 'TOGGLE_POSTS_LOADING',

  RECEIVE_TAGS: 'RECEIVE_TAGS',
  TOGGLE_TAGS_LOADING: 'TOGGLE_TAGS_LOADING',
};
